var xmasTreeShop3;
(function (xmasTreeShop3) {
    xmasTreeShop3.xmasTree = [{ name: "none,", price: 0 }, { name: "White Spruce,", price: 39.99 }, { name: "Serbian Spruce,", price: 39.99 }, { name: "Colorado Blue Spruce,", price: 39.99 }, { name: "Scots Pine,", price: 49.99 }, { name: "White Pine,", price: 49.99 }, { name: "Balsam Fir,", price: 45.99 }, { name: "Fraser Fir,", price: 45.99 }, { name: "Douglas Fir,", price: 45.99 }];
    xmasTreeShop3.xmasBulbs = [{ name: "none,", price: 0 }, { name: "purple,", price: 1.99 }, { name: "red,", price: 1.99 }, { name: "green,", price: 1.99 }, { name: "gold,", price: 2.99 }, { name: "silver,", price: 2.99 }, { name: "white,", price: 1.99 }, { name: "black,", price: 1.99 }, { name: "yellow,", price: 1.99 }, { name: "blue,", price: 1.99 }];
    xmasTreeShop3.xmasCandles = [{ name: "none,", price: 0 }, { name: "purple,", price: 1.99 }, { name: "red,", price: 1.99 }, { name: "green,", price: 1.99 }, { name: "gold,", price: 2.99 }, { name: "silver,", price: 2.99 }, { name: "white,", price: 1.99 }, { name: "black,", price: 1.99 }, { name: "yellow,", price: 1.99 }, { name: "blue,", price: 1.99 }];
    xmasTreeShop3.xmasOrnaments = [{ name: "none,", price: 0 }, { name: "Santa,", price: 4.99 }, { name: "Snowman,", price: 3.99 }, { name: "Star,", price: 2.99 }, { name: "Gingerbread man,", price: 3.99 }, { name: "Bell,", price: 2.99 }, { name: "Angel,", price: 3.99 }];
    xmasTreeShop3.lametta = [{ name: "none,", price: 0 }, { name: "Max,", price: 101.99 }, { name: "purple,", price: 1.99 }, { name: "red,", price: 1.99 }, { name: "green,", price: 1.99 }, { name: "gold,", price: 2.99 }, { name: "silver,", price: 2.99 }, { name: "white,", price: 1.99 }, { name: "black,", price: 1.99 }, { name: "yellow,", price: 1.99 }, { name: "blue,", price: 1.99 }];
    xmasTreeShop3.treeStands = [{ name: "black,", price: 9.99 }, { name: "brown,", price: 9.99 }, { name: "green,", price: 9.99 }, { name: "gold,", price: 11.99 }, { name: "silver,", price: 11.99 }];
    xmasTreeShop3.delivery = [{ name: "Standard", price: 25 }, { name: "Express", price: 34.99 }, { name: "Fast", price: 49.99 }];
})(xmasTreeShop3 || (xmasTreeShop3 = {}));
//# sourceMappingURL=merchant.js.map